import React from "react";
import { Calendar } from "lucide-react";

interface ExperienceItem {
  role?: string;
  position?: string;
  company?: string;
  duration?: string;
  start_date?: string;
  end_date?: string;
  achievements?: string[];
  responsibilities?: string[];
}

interface ExperienceSectionProps {
  experiences?: ExperienceItem[];
}

export default function ExperienceSection({
  experiences = [],
}: ExperienceSectionProps) {
  return (
    <div className="space-y-6">
      <div className="border-b border-border pb-3">
        <h2 className="text-[24px] font-heading font-semibold text-foreground">
          Professional Experience
        </h2>
      </div>

      <div className="space-y-8">
        {experiences && experiences.length > 0 ? (
          experiences.map((exp, index) => {
            const role = exp.role || exp.position || "Position";
            const company = exp.company || "Company";
            const duration =
              exp.duration ||
              (exp.start_date || exp.end_date
                ? `${exp.start_date || ""} - ${exp.end_date || "Present"}`
                : "Present");
            const achievements = exp.achievements || exp.responsibilities || [];

            return (
              <div key={index} className="space-y-3">
                {/* Header Company Details */}
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-1">
                  <div>
                    <h3 className="text-[20px] font-heading font-semibold text-foreground">
                      {role}
                    </h3>
                    <p className="text-[16px] font-sans text-primary/90 font-medium mt-0.5">
                      {company}
                    </p>
                  </div>
                  <div className="flex items-center gap-1.5 text-[14px] font-sans text-muted-foreground">
                    <Calendar className="w-4 h-4 text-muted-foreground/60" />
                    {duration}
                  </div>
                </div>

                {/* Achievements generated by AI */}
                {achievements.length > 0 && (
                  <ul className="list-disc list-outside pl-4 space-y-2 text-[14px] md:text-[16px] font-sans text-muted-foreground">
                    {achievements.map((achievement, actIndex) => (
                      <li key={actIndex} className="leading-relaxed">
                        {achievement}
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            );
          })
        ) : (
          <p className="text-[14px] font-sans text-muted-foreground">
            Belum ada riwayat kerja yang teranalisis.
          </p>
        )}
      </div>
    </div>
  );
}
